version: "3.1"
services:
    bot:
        build:
            context: .
            dockerfile: ./docker/bot/Dockerfile
        volumes:
            - ./src/bot:/code
            - ./logs:/logs
        env_file:
            - .env
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - "${HOST_DEV_PORT_BOT}:80"
        command: python main.py
        networks:
            - discord_bot_network
    api:
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        volumes:
            - ./src/api:/code
            - ./logs:/logs
        env_file:
            - .env
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - "${HOST_DEV_PORT_API}:5000"
        restart: always
        command: python main.py
        networks:
            - discord_bot_network
networks:
    discord_bot_network:
        external:
            name: discord_bot_network
